FROM openjdk:8-jdk-alpine

ARG APP_NAME
ARG APP_VER
ARG BUILD_NUMBER

VOLUME /tmp

LABEL APPLICATION_NAME=${APP_NAME}
LABEL APPLICATION_VERSION=${APP_VER}
LABEL BUILD_NUMBER=${BUILD_NUMBER}
LABEL APPLICATION_FULL_NAME=${APP_NAME}-${APP_VER}-${BUILD_NUMBER}

COPY ${APP_NAME}-${APP_VER}.jar /app.jar

ENV JAVA_OPTS="-XX:+UseG1GC -XX:+DisableExplicitGC"

EXPOSE 8080 8443

COPY run-java.sh /
RUN chmod 755 /run-java.sh

ENTRYPOINT [ "/run-java.sh" ]
